version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - SECRET_KEY=wlp0@mnr6z*#d%%0^mngtqwz03%u&^66%*qr)qk@)cu^-pn+ga
    volumes:
      - ./photography/media:/photography/media