# Generated by Django 2.0.5 on 2018-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='fivehundredpx',
            field=models.URLField(blank=True, help_text='Your 500px page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram page URL'),
        ),
    ]
