# Generated by Django 2.0.5 on 2018-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180519_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook_alttext',
            field=models.TextField(blank=True, help_text='If set this text will show instead of the Font Awesome logo'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='fivehundredpx_alttext',
            field=models.TextField(blank=True, help_text='If set this text will show instead of the Font Awesome logo'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram_alttext',
            field=models.TextField(blank=True, help_text='If set this text will show instead of the Font Awesome logo'),
        ),
    ]
