# Generated by Django 2.0.5 on 2018-05-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180519_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social Media Accounts'},
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='fivehundredpx',
            new_name='_500px',
        ),
    ]
