# Generated by Django 2.0.5 on 2018-05-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180519_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='fivehundredpx_alttext',
            new_name='_500px_alt_text',
        ),
    ]
