# Generated by Django 2.0.5 on 2018-05-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180519_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='_500px_alt_text',
            new_name='_500px_Text',
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='facebook_alttext',
            new_name='facebook_Text',
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='instagram_alttext',
            new_name='instagram_Text',
        ),
    ]
